# Generated by Django 4.2.6 on 2023-11-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoAnimal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Razas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raza', models.CharField(max_length=50)),
                ('tipoAnimal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipoanimal')),
            ],
        ),
    ]
