# Generated by Django 4.2.6 on 2023-11-06 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_animal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.razas'),
        ),
    ]
