# Generated by Django 4.2.6 on 2023-11-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_animal_raza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Razas',
            new_name='Raza',
        ),
    ]
