# Generated by Django 4.2.6 on 2023-11-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_rename_razas_raza'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoAnimal',
            new_name='Grupo',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='tipoAnimal',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='raza',
            old_name='tipoAnimal',
            new_name='grupo',
        ),
    ]
