# Generated by Django 4.2.6 on 2023-11-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0005_rename_tipoanimal_grupo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='animales/'),
        ),
    ]
