# Generated by Django 4.2.6 on 2023-11-15 00:32

import catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0009_alter_animal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=catalogos.models.imagen_rfid_path),
        ),
    ]
