# Generated by Django 4.2.6 on 2023-11-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0011_raza_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='rfid',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
