# Generated by Django 4.2.6 on 2023-11-21 05:56

import catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0016_sexo_alter_animal_imagen_animal_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fechaSalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=catalogos.models.imagen_rfid_path),
        ),
    ]
