# Generated by Django 4.2.6 on 2023-11-21 06:00

import catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0017_alter_animal_fechasalida_alter_animal_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='fechaLlegada',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fechaSalida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=catalogos.models.imagen_rfid_path),
        ),
    ]
