# Generated by Django 4.2.6 on 2023-11-21 06:18

import catalogos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0023_alter_animal_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='fechaSalida',
            new_name='fechaSalidas',
        ),
        migrations.AlterField(
            model_name='animal',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=catalogos.models.imagen_rfid_path),
        ),
    ]
